[2023-11-19 16:49:44,142] INFO _log() L187  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.0.225:5000 - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:44,159] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:52,241] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:52] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:52,261] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:52] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:52,432] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:52] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:52,434] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:52] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:52,436] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:52] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:56,527] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:56] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:56,546] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:56] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:56,547] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:56] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:56,547] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:56] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:49:56,690] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:49:56] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:50:23,224] ERROR log_exception() L1449 Exception on /addcliente [POST] - call_trace=C:\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "C:\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "C:\qaninja\tau-intro-to-pytest\tests\PÓS\api - Churn\app.py", line 83, in predict
    modelo = Model.carrega_modelo(ml_path)
  File "C:\qaninja\tau-intro-to-pytest\tests\PÓS\api - Churn\model\modelo.py", line 12, in carrega_modelo
    model = pickle.load(open(path, 'rb'))
  File "sklearn\tree\_tree.pyx", line 728, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn\tree\_tree.pyx", line 1434, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
[2023-11-19 16:50:23,230] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:50:23] "[35m[1mPOST /addcliente HTTP/1.1[0m" 500 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:43,681] INFO _log() L187  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.0.225:5000 - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:43,687] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:45,586] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:58:45] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:45,762] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:58:45] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:45,763] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:58:45] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:45,763] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:58:45] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:45,844] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:58:45] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:45,849] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:58:45] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
[2023-11-19 16:58:54,696] INFO _log() L187  127.0.0.1 - - [19/Nov/2023 16:58:54] "POST /addcliente HTTP/1.1" 200 - - call_trace=C:\Python310\lib\site-packages\werkzeug\_internal.py L187 
